- name: dist-upgrade
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: true
  tasks:
    
  
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes     
